name: Publish Packages

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-restore

      - name: Pack Hitch
        run: dotnet pack src/Hitch/Hitch.csproj --configuration Release --no-build --output ./nupkgs

      - name: Push Hitch package to NuGet
        run: dotnet nuget push ./nupkgs/Hitch.*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Pack Hitch.Aspire.Hosting
        run: dotnet pack src/Hitch.Aspire.Hosting/Hitch.Aspire.Hosting.csproj --configuration Release --no-build --output ./nupkgs

      - name: Push Hitch.Aspire.Hosting package to NuGet
        run: dotnet nuget push ./nupkgs/Hitch.Aspire.Hosting.*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
